@startuml fakultas
title Jadwal dan Nilai Mahasiswa Fakultas

start

:Buka Aplikasi;

:Masukkan Email dan Password;

if (Email dan Password Valid?) then (Ya)
    if (Admin?) then (Ya)
        :Login Sebagai Admin;
        :Akses Manajemen Perkuliahan;
        :Pilih Aksi;
        if (Aksi = Tambah Perkuliahan) then (Tambah Perkuliahan)
            :Masukkan Detail Matakuliah dan Dosen;
            :Simpan Perkuliahan;
        else (Aksi = Edit Perkuliahan) then (Edit Perkuliahan)
            :Pilih Perkuliahan yang Akan Diedit;
            :Perbarui Detail Perkuliahan;
            :Simpan Perubahan;
        endif
        :Logout;
    elseif (Dosen?) then (Ya)
        :Login Sebagai Dosen;
        :Akses Manajemen Matakuliah;
        :Pilih Aksi;
        if (Aksi = Edit Materi) then (Edit Materi)
            :Masukkan Detail Materi;
            :Simpan Perubahan;
        else (Aksi = Edit Nilai) then (Edit Nilai)
            :Pilih Nilai yang Akan Diedit;
            :Perbarui Detail Perkuliahan;
            :Simpan Perubahan;
        endif
        :Logout;
    else (Mahasiswa)
        :Login Sebagai Mahasiswa;
        :Akses Tampilan Perkuliahan;
        :Tampilkan Detail Matakuliah (ID Matakuliah, Matakuliah, Dosen, Waktu, Durasi, Ruang, Nilai);
        if (Aksi = Tambah Matakuliah) then (Tambah Matakuliah)
            :Pilih Matakuliah;
            :Simpan Perubahan;
        endif
        :Logout;
    endif
else (Tidak)
    :Tampilkan "Email atau Password Tidak Valid";
    :Kembali ke Halaman Login;
endif

stop

@enduml