@startuml jadwal
actor Admin
actor Dosen
actor Mahasiswa

usecase "Input Email dan Password" as UC1
usecase "Cek Kredensial" as UC2
usecase "Login Gagal" as UC3
usecase "Login Admin/Dekan" as UC4
usecase "Login Mahasiswa" as UC5
usecase "Login Dosen" as UC6
usecase "Akses Manajemen Perkuliahan" as UC7
usecase "Akses Jadwal Perkuliahan" as UC8
usecase "Tambah Jadwal Perkuliahan" as UC9
usecase "Edit Jadwal Perkuliahan" as UC10
usecase "Edit Nilai Mata Kuliah" as UC11
usecase "Akses Nilai Mata Kuliah" as UC12
usecase "Akses Mata Kuliah" as UC13
usecase "Edit Mata Kuliah" as UC14
usecase "Tambah Mata Kuliah" as UC16
usecase "Logout" as UC15

Admin --> UC1
Dosen --> UC1
Mahasiswa --> UC1
UC1 --> UC2
UC2 --> UC3: tidak valid
UC3 --> UC1

UC1 --> UC4: valid
UC4 --> UC7
UC7 --> UC9: include
UC7 --> UC10: include
UC4 --> UC15 : extend

UC1 --> UC5: valid
UC5 --> UC8
UC5 --> UC12
UC12 --> UC16: include
UC5 --> UC15 : extend

UC1 --> UC6: valid
UC6 --> UC8
UC6 --> UC12
UC12 --> UC11: include
UC6 --> UC13
UC13 --> UC14: include
UC6 --> UC15 : extend

@enduml